### ISSUE TITLE
virus found

### ISSUE THREAD

**Issue by JasonDeving** [ThioJoe/YouTube-Spammer-Purge#34]
virus found virus total on .exe

https://www.virustotal.com/gui/file/898cc99415f426518ff418ebdc21c09e28df939f90a2869a566c965fec92d5c0

please fix

**Comment by flexagoon** [comment]
One detection by some random unknown antivirus out of 66 is probably not a concern. That warning is because the exe file is created with PyInstaller. pyinstaller was detected as a virus by most major antiviruses a while ago, but now most of them fixed this issue. It just looks like `Antiy-AVL` (whatever that is) just haven't fixed it yet.

**Comment by ThioJoe** [comment]
It's not a virus

**Comment by ArjixWasTaken** [comment]
even if it was a virus, the code is open source and you can directly run it without using the given exe...

**Comment by ThioJoe** [comment]
Pyinstaller tends to apparently create a bunch of false positives. In the latest release, it no longer triggers Antiy-AVL but now triggers something called "Jiangmin" 🤷‍♂️

Apparently this can sometimes be fixed by compiling the pyinstaller 'bootloader' yourself, so I'll attempt that when I get the chance.

**Comment by ArjixWasTaken** [comment]
Might want to give [nuitka](https://nuitka.net/) a look

**Comment by ThioJoe** [comment]
I compiled the pyinstaller bootloader myself and that seems to have fixed the false positives. The latest release (v1.4.0) has zero positives on virustotal.

I tried setting up Nuitka but couldn't really get it to work for some reason. But pyinstaller works now so it's fine.
