### ISSUE TITLE
Colored Text Feature

### ISSUE THREAD

**Issue by cob16** [ThioJoe/YouTube-Spammer-Purge#67]
Hey @ThioJoe  :wave: 

 I am wanted to make a PR to add features from your roadmap :smile:  
As Colored Text is up next I would like to take a stab at that.
From experience getting colours to work without breaking cross-platform support is a little bit difficult so I often use a library to do it
Colorama seems the most mature of these https://github.com/tartley/colorama

But as the [contributing guidelines](https://github.com/ThioJoe/YouTube-Spammer-Purge/blob/main/CONTRIBUTING.md#contributing-guidelines) ask to open an issue before adding a new library, Here I am asking :sweat_smile:

**Comment by ThioJoe** [comment]
I'd actually hold off, I'm going to try and implement a GUI because some new features require the display of unicode characters and emoji (which windows console can't do). Instead of going through the trouble of implementing a different console I figure I'll give a crack at a GUI instead, which I planned eventually anyway.

**Comment by ThioJoe** [comment]
I actually ended up just adding colors today. They're in the latest commit and will be in the next major build release.

**Comment by cob16** [comment]
No worries glad you used my library suggestion :+1:
